### ISSUE TITLE
KODI 19.1 Matrix errors

### ISSUE THREAD

**Issue by expertup** [pikim/script.service.kodi.callbacks#1]
I have try run this extension on Kodi 19.1. I changed `addon="xbmc.python"` to `version="3.0.0"`. 

I know that python 2.0 is diffrent to 3.0, but maybe We can try remake this extensin to Py 3.0 version

Here are logs:

```
2021-07-06 10:07:29.584 T:2368    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'tasks'
                                                   Traceback (most recent call last):
                                                     File "C:\Program Files\Kodi\addons\script.service.kodi.callbacks\default.py", line 27, in <module>
                                                       from resources.lib.utils.debugger import startdebugger
                                                     File "C:\Program Files\Kodi\addons\script.service.kodi.callbacks\resources\lib\__init__.py", line 23, in <module>
                                                       import tasks
                                                   ModuleNotFoundError: No module named 'tasks'
                                                   -->End of Python script error report<--
                                                   
2021-07-06 10:07:29.602 T:2368     INFO <general>: Python interpreter stopped
2021-07-06 10:07:34.726 T:8976     INFO <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
2021-07-06 10:08:25.119 T:8976     INFO <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2021-07-06 10:08:38.608 T:8976     INFO <general>: Loading skin file: EventLog.xml, load type: KEEP_IN_MEMORY
2021-07-06 10:32:57.548 T:12316    INFO <general>: initializing python engine.
2021-07-06 10:32:57.782 T:12316   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'tasks'
                                                   Traceback (most recent call last):
                                                     File "C:\Program Files\Kodi\addons\script.service.kodi.callbacks\script.py", line 25, in <module>
                                                       import resources.lib.pubsub as PubSub_Threaded
                                                     File "C:\Program Files\Kodi\addons\script.service.kodi.callbacks\resources\lib\__init__.py", line 23, in <module>
                                                       import tasks
                                                   ModuleNotFoundError: No module named 'tasks'
                                                   -->End of Python script error report<--
                                                   
2021-07-06 10:32:57.793 T:11212    INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-07-06 10:32:57.805 T:12316    INFO <general>: Python interpreter stopped
2021-07-06 10:33:03.976 T:13280    INFO <general>: initializing python engine.
2021-07-06 10:33:04.228 T:13280   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'tasks'
                                                   Traceback (most recent call last):
                                                     File "C:\Program Files\Kodi\addons\script.service.kodi.callbacks\script.py", line 25, in <module>
                                                       import resources.lib.pubsub as PubSub_Threaded
                                                     File "C:\Program Files\Kodi\addons\script.service.kodi.callbacks\resources\lib\__init__.py", line 23, in <module>
                                                       import tasks
                                                   ModuleNotFoundError: No module named 'tasks'
                                                   -->End of Python script error report<--
                                                   
2021-07-06 10:33:04.249 T:13280    INFO <general>: Python interpreter stopped
```

What is this error about?
That the `tasks` extension is missing or that the `tasks` extension is for an older version of python?

**Comment by pikim** [comment]
I don't know what you're trying to do. This version is already updated, so that it generally runs on KODI 19.x with Python 3. It's not fully tested, yet. And according to the forum some functionality doesn't work, but I wasn't able to find and fix the issue, yet.
